#ifndef HELLOKIT_DOCUMENT_HELLOKITDOCUMENTGLOBAL_H
#define HELLOKIT_DOCUMENT_HELLOKITDOCUMENTGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_DOCUMENT_EXPORT
#  ifdef HELLOKIT_DOCUMENT_STATIC
#    define HELLOKIT_DOCUMENT_EXPORT
#  else
#    ifdef HELLOKIT_DOCUMENT_LIBRARY
#      define HELLOKIT_DOCUMENT_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_DOCUMENT_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_DOCUMENT_HELLOKITDOCUMENTGLOBAL_H
