#ifndef HELLOKIT_DOCUMENT_HELLOKITUSTGLOBAL_H
#define HELLOKIT_DOCUMENT_HELLOKITUSTGLOBAL_H

#include <stdcorelib/stdc_global.h>

#ifndef HELLOKIT_DOCUMENT_EXPORT
#  ifdef HELLOKIT_DOCUMENT_STATIC
#    define HELLOKIT_DOCUMENT_EXPORT
#  else
#    ifdef HELLOKIT_DOCUMENT_LIBRARY
#      define HELLOKIT_DOCUMENT_EXPORT STDC_DECL_EXPORT
#    else
#      define HELLOKIT_DOCUMENT_EXPORT STDC_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_DOCUMENT_HELLOKITUSTGLOBAL_H
