#ifndef HELLOUTAU_EDITOR_HELLOUTAUEDITORGLOBAL_H
#define HELLOUTAU_EDITOR_HELLOUTAUEDITORGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOUTAU_EDITOR_EXPORT
#  ifdef HELLOUTAU_EDITOR_STATIC
#    define HELLOUTAU_EDITOR_EXPORT
#  else
#    ifdef HELLOUTAU_EDITOR_LIBRARY
#      define HELLOUTAU_EDITOR_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOUTAU_EDITOR_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_EDITOR_HELLOUTAUEDITORGLOBAL_H
