#include "ClassicPluginContribution.h"

#include <system_error>

#include <QtCore/QPointer>
#include <QtCore/QStandardPaths>
#include <QtCore/QUrl>
#include <QtGui/QAction>
#include <QtGui/QCursor>
#include <QtGui/QDesktopServices>
#include <QtWidgets/QMenu>

#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Editor/AppSettings.h>
#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>

#include "ClassicPluginRun.h"

// Generated by qak_add_action_extension() from ClassicPluginActions.xml
#include "ClassicPluginActions.qak.h"

namespace hello::daw {

    namespace {

        std::filesystem::path pluginsOf(const std::filesystem::path &utauDirectory) {
            return utauDirectory.empty() ? std::filesystem::path() : utauDirectory / u"plugins";
        }

    }

    QList<std::filesystem::path>
        ClassicPluginContribution::pluginFolders(const AppSettings &settings) {
        // The plugin folder of HelloUtau precedes the plugins folder of UTAU, as with the voice
        // folders of AppSettings::voiceLocations().
        QList<std::filesystem::path> folders{userDirectory()};
        if (const auto utauPlugins = pluginsOf(settings.utauDirectory()); !utauPlugins.empty()) {
            folders.push_back(utauPlugins);
        }
        return folders;
    }

    void ClassicPluginContribution::openFolder(const std::filesystem::path &folder) {
        std::error_code error;
        std::filesystem::create_directories(folder, error);
        QDesktopServices::openUrl(
            QUrl::fromLocalFile(QString::fromStdU16String(folder.u16string())));
    }

    ClassicPluginContribution::ClassicPluginContribution() = default;

    ClassicPluginContribution::~ClassicPluginContribution() = default;

    // The plugins of UTAU edit the notes of a project, so the commands are in the project window
    // alone.
    const QAK::ActionExtension *
        ClassicPluginContribution::extension(const QString &windowKind) const {
        return windowKind == QLatin1String(Editor::projectWindowName) ? classicPluginActions()
                                                                      : nullptr;
    }

    void ClassicPluginContribution::addActions(QWidget *widget, QAK::WidgetActionContext *context) {
        const auto window = qobject_cast<ProjectWindow *>(widget);
        if (!window) {
            return;
        }
        // An external action. This plugin fills its menu each time the menu opens.
        const auto menu = new QMenu(window);
        menu->setToolTipsVisible(true);
        QObject::connect(menu, &QMenu::aboutToShow, menu,
                         [this, menu, window] { fill(menu, window); });
        // Converted from UTF-8 rather than a literal, whose data would be unloaded with this
        // library
        context->addAction(QString::fromUtf8("helloutau.tools.classicPlugins"), menu->menuAction());

        // The menu at the mouse pointer. The action is in no menu, so the window holds it for its
        // shortcut to take effect.
        const auto atPointer = new QAction(window);
        window->addAction(atPointer);
        const QPointer<QMenu> guarded(menu);
        QObject::connect(atPointer, &QAction::triggered, window, [guarded] {
            if (guarded) {
                guarded->popup(QCursor::pos());
            }
        });
        context->addAction(QString::fromUtf8("helloutau.tools.classicPluginsAtPointer"), atPointer);
    }

    std::filesystem::path ClassicPluginContribution::userDirectory() {
        return std::filesystem::path(
                   QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)
                       .toStdU16String()) /
               u"UtauPlugins";
    }

    void ClassicPluginContribution::fill(QMenu *menu, ProjectWindow *window) {
        if (m_utauDirectory != window->editor()->settings().utauDirectory()) {
            refresh(window);
        }

        menu->clear();
        for (const auto &plugin : std::as_const(m_plugins)) {
            // The name is plain text. An ampersand in it is not a mnemonic.
            auto name = plugin.name;
            const auto action =
                menu->addAction(name.replace(QLatin1Char('&'), QLatin1String("&&")));
            action->setEnabled(plugin.isAvailable());
            action->setToolTip(plugin.unavailableReason);
            QObject::connect(action, &QAction::triggered, window,
                             [window, plugin] { runClassicPlugin(window, plugin); });
        }
        if (m_plugins.isEmpty()) {
            menu->addAction(tr("No Plugins"))->setEnabled(false);
        }

        menu->addSeparator();
        QObject::connect(menu->addAction(tr("&Refresh")), &QAction::triggered, window,
                         [this, window] { refresh(window); });
        QObject::connect(menu->addAction(tr("&Open Plugin Folder")), &QAction::triggered, window,
                         [] { openFolder(userDirectory()); });
        const auto utauPlugins = pluginsOf(window->editor()->settings().utauDirectory());
        if (!utauPlugins.empty()) {
            QObject::connect(menu->addAction(tr("Open &UTAU Plugin Folder")), &QAction::triggered,
                             window, [utauPlugins] { openFolder(utauPlugins); });
        }
    }

    void ClassicPluginContribution::refresh(ProjectWindow *window) {
        const auto &settings = window->editor()->settings();
        // A folder that does not exist yields no plugins, and a folder whose plugin.txt cannot
        // be read is skipped, as in UTAU.
        kit::DiagnosticList diagnostics;
        m_plugins = ClassicPlugin::discover(pluginFolders(settings), diagnostics);
        m_utauDirectory = settings.utauDirectory();
    }

}
