#include "ClassicPluginContribution.h"

#include <system_error>

#include <QtCore/QStandardPaths>
#include <QtCore/QUrl>
#include <QtGui/QAction>
#include <QtGui/QDesktopServices>
#include <QtWidgets/QMenu>

#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Editor/AppSettings.h>
#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>

#include "ClassicPluginRun.h"

// Generated by qak_add_action_extension() from ClassicPluginActions.xml
#include "ClassicPluginActions.qak.h"

namespace hello::daw {

    namespace {

        std::filesystem::path pluginsOf(const std::filesystem::path &utauDirectory) {
            return utauDirectory.empty() ? std::filesystem::path() : utauDirectory / u"plugins";
        }

        // Opens \a directory in the file manager, creating it if need be.
        void open(const std::filesystem::path &directory) {
            std::error_code error;
            std::filesystem::create_directories(directory, error);
            QDesktopServices::openUrl(
                QUrl::fromLocalFile(QString::fromStdU16String(directory.u16string())));
        }

    }

    ClassicPluginContribution::ClassicPluginContribution() = default;

    ClassicPluginContribution::~ClassicPluginContribution() = default;

    const QAK::ActionExtension *ClassicPluginContribution::extension() const {
        return classicPluginActions();
    }

    void ClassicPluginContribution::addActions(ProjectWindow *window,
                                               QAK::WidgetActionContext *context) {
        // An external action: its menu is ours to fill, each time it opens.
        const auto menu = new QMenu(window);
        menu->setToolTipsVisible(true);
        QObject::connect(menu, &QMenu::aboutToShow, menu,
                         [this, menu, window] { fill(menu, window); });
        // Copied from UTF-8 rather than a literal, whose text would go with this library
        context->addAction(QString::fromUtf8("helloutau.tools.plugins"), menu->menuAction());
    }

    std::filesystem::path ClassicPluginContribution::userDirectory() {
        return std::filesystem::path(
                   QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)
                       .toStdU16String()) /
               u"UtauPlugins";
    }

    void ClassicPluginContribution::fill(QMenu *menu, ProjectWindow *window) {
        if (m_utauDirectory != window->editor()->settings().utauDirectory()) {
            refresh(window);
        }

        menu->clear();
        for (const auto &plugin : std::as_const(m_plugins)) {
            // A name is text, and an ampersand in it no mnemonic.
            auto name = plugin.name;
            const auto action =
                menu->addAction(name.replace(QLatin1Char('&'), QLatin1String("&&")));
            action->setEnabled(plugin.isAvailable());
            action->setToolTip(plugin.unavailableReason);
            QObject::connect(action, &QAction::triggered, window,
                             [window, plugin] { runClassicPlugin(window, plugin); });
        }
        if (m_plugins.isEmpty()) {
            menu->addAction(tr("No Plugins"))->setEnabled(false);
        }

        menu->addSeparator();
        QObject::connect(menu->addAction(tr("&Refresh")), &QAction::triggered, window,
                         [this, window] { refresh(window); });
        QObject::connect(menu->addAction(tr("&Open Plugin Folder")), &QAction::triggered, window,
                         [] { open(userDirectory()); });
        const auto utauPlugins = pluginsOf(window->editor()->settings().utauDirectory());
        if (!utauPlugins.empty()) {
            QObject::connect(menu->addAction(tr("Open &UTAU Plugin Folder")), &QAction::triggered,
                             window, [utauPlugins] { open(utauPlugins); });
        }
    }

    void ClassicPluginContribution::refresh(ProjectWindow *window) {
        const auto utauDirectory = window->editor()->settings().utauDirectory();
        QList<std::filesystem::path> directories;
        if (const auto utauPlugins = pluginsOf(utauDirectory); !utauPlugins.empty()) {
            directories.push_back(utauPlugins);
        }
        directories.push_back(userDirectory());

        // A plugin.txt that cannot be read leaves its folder out, as UTAU does.
        kit::DiagnosticList diagnostics;
        m_plugins = ClassicPlugin::discover(directories, diagnostics);
        m_utauDirectory = utauDirectory;
    }

}
