#include "BuiltinActions.h"

#include <memory>

#include "AppLoader.h"
#include "Editor.h"

// Generated by qak_add_action_extension() from ProjectActions.xml and VoiceBankActions.xml
#include "ProjectActions.qak.h"
#include "VoiceBankActions.qak.h"

namespace hello::daw {

    namespace {

        // Contribution of the extension of each kind of window, whose actions the windows
        // create themselves
        class WindowsContribution : public ActionContribution {
        public:
            const QAK::ActionExtension *extension(const QString &windowKind) const override {
                if (windowKind == QLatin1String(Editor::projectWindowName)) {
                    return projectActions();
                }
                if (windowKind == QLatin1String(Editor::voiceBankWindowName)) {
                    return voiceBankActions();
                }
                return nullptr;
            }
        };

    }

    BuiltinActions::BuiltinActions(Editor *editor)
        : QObject(editor),
          m_registration(editor->actionContributions(), AppLoader::corePluginId, {},
                         [] { return std::make_unique<WindowsContribution>(); }) {
    }

    BuiltinActions::~BuiltinActions() = default;

}
