#include "BuiltinActions.h"

#include "ActionRegistration.h"

// Generated by qak_add_action_extension() from ProjectActions.xml and VoiceBankActions.xml
#include "ProjectActions.qak.h"
#include "VoiceBankActions.qak.h"

namespace hello::daw {

    namespace {

        // Contribution of the extension of each kind of window, whose actions the windows
        // create themselves
        class WindowsContribution : public ActionContribution {
        public:
            const QAK::ActionExtension *extension(Editor::WindowKind kind) const override {
                switch (kind) {
                    case Editor::ProjectWindowKind:
                        return projectActions();
                    case Editor::VoiceBankWindowKind:
                        return voiceBankActions();
                }
                return nullptr;
            }
        };

    }

    BuiltinActions::BuiltinActions()
        : m_registration(
              std::make_unique<ActionRegistration>(std::make_unique<WindowsContribution>())) {
    }

    BuiltinActions::~BuiltinActions() = default;

}
