#include "BuiltinActions.h"

#include "ActionRegistration.h"

// Generated by qak_add_action_extension() from AppActions.xml and EditorActions.xml
#include "AppActions.qak.h"
#include "EditorActions.qak.h"

namespace hello::daw {

    namespace {

        // An extension whose actions the windows create themselves
        class ExtensionContribution : public ActionContribution {
        public:
            explicit ExtensionContribution(const QAK::ActionExtension *extension)
                : m_extension(extension) {
            }

            const QAK::ActionExtension *extension() const override {
                return m_extension;
            }

        private:
            const QAK::ActionExtension *m_extension;
        };

        std::unique_ptr<ActionRegistration> registration(const QAK::ActionExtension *extension) {
            return std::make_unique<ActionRegistration>(
                std::make_unique<ExtensionContribution>(extension));
        }

    }

    BuiltinActions::BuiltinActions()
        : m_app(registration(appActions())), m_windows(registration(editorActions())) {
    }

    BuiltinActions::~BuiltinActions() = default;

}
