#include "Editor.h"

#include <QtCore/QDir>
#include <QtCore/QPointer>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMessageBox>

#include <stdcorelib/pimpl.h>

#include <QAKCore/actionregistry.h>

#include <hellokit/Edit/ProjectDocument.h>
#include <hellokit/Edit/VoiceBankDocument.h>

#include <helloutau/Theme/ThemeManager.h>

#include "AppSettings.h"
#include "DiagnosticBox_p.h"
#include "MainWindow.h"
#include "UstCharsetDialog.h"
#include "VoiceBankCharsetDialog.h"
#include "VoiceBankWindow.h"

// Generated by qak_add_action_extension() from EditorActions.xml
#include "EditorActions.qak.h"

namespace hello::daw {

    namespace {

        QString textOf(const std::filesystem::path &path) {
            return QString::fromStdU16String(path.u16string());
        }

        bool isSameFile(const std::filesystem::path &a, const std::filesystem::path &b) {
            if (a.empty() || b.empty()) {
                return false;
            }
            std::error_code error;
            return std::filesystem::equivalent(a, b, error);
        }

    }

    class Editor::Impl {
    public:
        using Decl = Editor;

        explicit Impl(std::unique_ptr<AppSettings> settings) : settings(std::move(settings)) {
        }

        std::unique_ptr<AppSettings> settings;
        QAK::ActionRegistry *registry = nullptr;
        ThemeManager *themes = nullptr;
        QList<QPointer<MainWindow>> windows;
        QList<QPointer<VoiceBankWindow>> voiceBankWindows;

        MainWindow *createWindow(Editor *editor, std::unique_ptr<kit::ProjectDocument> document) {
            auto window = new MainWindow(editor, std::move(document));
            window->setAttribute(Qt::WA_DeleteOnClose);
            windows.removeAll(nullptr);
            windows.push_back(window);
            window->show();
            return window;
        }
    };

    Editor::Editor(QObject *parent) : Editor(std::make_unique<AppSettings>(), parent) {
    }

    Editor::Editor(std::unique_ptr<AppSettings> settings, QObject *parent)
        : QObject(parent), _impl(std::make_unique<Impl>(std::move(settings))) {
        stdc_impl_t;
        impl.registry = new QAK::ActionRegistry(this);
        impl.registry->setExtensions({editorActions()});
        impl.themes = new ThemeManager(this);
        impl.themes->addSearchPath(QStringLiteral(":/helloutau/themes"));
    }

    Editor::~Editor() {
        stdc_impl_t;
        // The windows refer to the registry and the settings, so they go first.
        for (const auto &window : std::as_const(impl.windows)) {
            delete window.data();
        }
        for (const auto &window : std::as_const(impl.voiceBankWindows)) {
            delete window.data();
        }
    }

    AppSettings &Editor::settings() const {
        stdc_impl_t;
        return *impl.settings;
    }

    QAK::ActionRegistry *Editor::actionRegistry() const {
        stdc_impl_t;
        return impl.registry;
    }

    ThemeManager *Editor::themeManager() const {
        stdc_impl_t;
        return impl.themes;
    }

    QList<MainWindow *> Editor::windows() const {
        stdc_impl_t;
        QList<MainWindow *> result;
        for (const auto &window : std::as_const(impl.windows)) {
            if (window) {
                result.push_back(window);
            }
        }
        return result;
    }

    MainWindow *Editor::newWindow() {
        stdc_impl_t;
        return impl.createWindow(this, std::make_unique<kit::ProjectDocument>());
    }

    MainWindow *Editor::openFile(const std::filesystem::path &path, MainWindow *from) {
        stdc_impl_t;
        for (const auto window : windows()) {
            if (isSameFile(window->document()->sourcePath(), path)) {
                window->raise();
                window->activateWindow();
                return window;
            }
        }

        UstCharsetDialog selector(from);
        kit::DiagnosticList diagnostics;
        auto document = kit::ProjectDocument::open(path, &selector, diagnostics);
        const auto title =
            tr("Open %1").arg(QString::fromStdU16String(path.filename().u16string()));
        if (!document) {
            DiagnosticBox::show(from, title, diagnostics);
            return nullptr;
        }
        impl.settings->addRecentFile(path);

        MainWindow *window = from;
        if (window && window->isUnused()) {
            window->setDocument(std::move(document));
        } else {
            window = impl.createWindow(this, std::move(document));
        }
        // Shown after the window, so that the user sees which project they concern, and before
        // the voice bank is read, which may ask more.
        DiagnosticBox::show(window, title, diagnostics);
        window->loadVoiceBank();
        return window;
    }

    QList<VoiceBankWindow *> Editor::voiceBankWindows() const {
        stdc_impl_t;
        QList<VoiceBankWindow *> result;
        for (const auto &window : std::as_const(impl.voiceBankWindows)) {
            if (window) {
                result.push_back(window);
            }
        }
        return result;
    }

    VoiceBankWindow *Editor::openVoiceBank(const std::filesystem::path &root, QWidget *from) {
        stdc_impl_t;
        for (const auto window : voiceBankWindows()) {
            if (isSameFile(window->document()->rootPath(), root)) {
                window->raise();
                window->activateWindow();
                return window;
            }
        }
        VoiceBankCharsetDialog selector(from);
        selector.setRoot(root);
        kit::DiagnosticList diagnostics;
        auto document = kit::VoiceBankDocument::open(root, &selector, diagnostics);
        const auto title = tr("Open %1").arg(QDir::toNativeSeparators(textOf(root)));
        if (!document) {
            DiagnosticBox::show(from, title, diagnostics);
            return nullptr;
        }
        auto window = new VoiceBankWindow(this, std::move(document));
        window->setAttribute(Qt::WA_DeleteOnClose);
        impl.voiceBankWindows.removeAll(nullptr);
        impl.voiceBankWindows.push_back(window);
        window->show();
        DiagnosticBox::show(window, title, diagnostics);
        return window;
    }

    void Editor::fillRecentMenu(QMenu *menu, QWidget *from) {
        stdc_impl_t;
        menu->clear();
        const auto files = impl.settings->recentFiles();
        if (files.isEmpty()) {
            menu->addAction(tr("No Recent Files"))->setEnabled(false);
            return;
        }
        const auto project = qobject_cast<MainWindow *>(from);
        for (qsizetype i = 0; i < files.size(); ++i) {
            const auto path = files[i];
            const auto text = QDir::toNativeSeparators(textOf(path));
            // Numbered 1 to 9 and then 0, as the keys of the first ten
            const auto action = menu->addAction(
                QStringLiteral("&%1 %2")
                    .arg((i + 1) % 10)
                    .arg(QString(text).replace(QLatin1Char('&'), QStringLiteral("&&"))));
            connect(action, &QAction::triggered, menu, [this, path, from, project] {
                stdc_impl_t;
                std::error_code error;
                if (!std::filesystem::is_regular_file(path, error)) {
                    QMessageBox::warning(
                        from, tr("Open Recent"),
                        tr("%1 no longer exists.").arg(QDir::toNativeSeparators(textOf(path))));
                    impl.settings->removeRecentFile(path);
                    return;
                }
                openFile(path, project);
            });
        }
        menu->addSeparator();
        connect(menu->addAction(tr("&Clear Recent Files")), &QAction::triggered, menu, [this] {
            stdc_impl_t;
            impl.settings->clearRecentFiles();
        });
    }

    bool Editor::closeAll() {
        for (const auto window : windows()) {
            if (!window->close()) {
                return false;
            }
        }
        for (const auto window : voiceBankWindows()) {
            if (!window->close()) {
                return false;
            }
        }
        return true;
    }

}
