#include "Editor.h"

#include <QtCore/QPointer>

#include <QAKCore/actionregistry.h>

#include <hellokit/Edit/ProjectDocument.h>

#include <helloutau/Theme/ThemeManager.h>

#include "AppSettings.h"
#include "DiagnosticBox_p.h"
#include "MainWindow.h"
#include "UstCharsetDialog.h"

// Generated by qak_add_action_extension() from EditorActions.xml
#include "EditorActions.qak.h"

namespace hello::daw {

    namespace {

        bool isSameFile(const std::filesystem::path &a, const std::filesystem::path &b) {
            if (a.empty() || b.empty()) {
                return false;
            }
            std::error_code error;
            return std::filesystem::equivalent(a, b, error);
        }

    }

    class Editor::Impl {
    public:
        explicit Impl(std::unique_ptr<AppSettings> settings) : settings(std::move(settings)) {
        }

        std::unique_ptr<AppSettings> settings;
        QAK::ActionRegistry *registry = nullptr;
        ThemeManager *themes = nullptr;
        QList<QPointer<MainWindow>> windows;

        MainWindow *createWindow(Editor *editor, std::unique_ptr<kit::ProjectDocument> document) {
            auto window = new MainWindow(editor, std::move(document));
            window->setAttribute(Qt::WA_DeleteOnClose);
            windows.removeAll(nullptr);
            windows.push_back(window);
            window->show();
            return window;
        }
    };

    Editor::Editor(QObject *parent) : Editor(std::make_unique<AppSettings>(), parent) {
    }

    Editor::Editor(std::unique_ptr<AppSettings> settings, QObject *parent)
        : QObject(parent), _impl(std::make_unique<Impl>(std::move(settings))) {
        _impl->registry = new QAK::ActionRegistry(this);
        _impl->registry->setExtensions({editorActions()});
        _impl->themes = new ThemeManager(this);
        _impl->themes->addSearchPath(QStringLiteral(":/helloutau/themes"));
    }

    Editor::~Editor() {
        // The windows refer to the registry and the settings, so they go first.
        for (const auto &window : std::as_const(_impl->windows)) {
            delete window.data();
        }
    }

    AppSettings &Editor::settings() const {
        return *_impl->settings;
    }

    QAK::ActionRegistry *Editor::actionRegistry() const {
        return _impl->registry;
    }

    ThemeManager *Editor::themeManager() const {
        return _impl->themes;
    }

    QList<MainWindow *> Editor::windows() const {
        QList<MainWindow *> result;
        for (const auto &window : std::as_const(_impl->windows)) {
            if (window) {
                result.push_back(window);
            }
        }
        return result;
    }

    MainWindow *Editor::newWindow() {
        return _impl->createWindow(this, std::make_unique<kit::ProjectDocument>());
    }

    MainWindow *Editor::openFile(const std::filesystem::path &path, MainWindow *from) {
        for (const auto window : windows()) {
            if (isSameFile(window->document()->sourcePath(), path)) {
                window->raise();
                window->activateWindow();
                return window;
            }
        }

        UstCharsetDialog selector(from);
        kit::DiagnosticList diagnostics;
        auto document = kit::ProjectDocument::open(path, &selector, diagnostics);
        const auto title =
            tr("Open %1").arg(QString::fromStdU16String(path.filename().u16string()));
        if (!document) {
            DiagnosticBox::show(from, title, diagnostics);
            return nullptr;
        }

        MainWindow *window = from;
        if (window && window->isUnused()) {
            window->setDocument(std::move(document));
        } else {
            window = _impl->createWindow(this, std::move(document));
        }
        // Shown after the window, so that the user sees which project they concern, and before
        // the voice bank is read, which may ask more.
        DiagnosticBox::show(window, title, diagnostics);
        window->loadVoiceBank();
        return window;
    }

    bool Editor::closeAll() {
        for (const auto window : windows()) {
            if (!window->close()) {
                return false;
            }
        }
        return true;
    }

}
