#include "NoteViewModifiers.h"

#include <QtCore/QCoreApplication>

namespace hello::daw {

    const ModifierScheme &NoteViewModifiers::scheme() {
        constexpr auto ctrl = Qt::ControlModifier;
        constexpr auto alt = Qt::AltModifier;
        constexpr auto shift = Qt::ShiftModifier;
        constexpr auto none = Qt::NoModifier;
        // The drag that zooms, an operation of every left drag scene
        const ModifierScheme::Operation zoom{DragZoom, {DragZoomAxisLock}};
        static const ModifierScheme scheme(
            "noteView", "hello::daw::NoteViewModifiers",
            QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Note Area"),
            {
                {VerticalScroll, "verticalScroll",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Wheel: Scroll Vertically"),
                 none},
                {HorizontalScroll, "horizontalScroll",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Wheel: Scroll Horizontally"),
                 shift},
                {TimeZoom, "timeZoom",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Wheel: Zoom Time"), ctrl},
                {KeyZoom, "keyZoom",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Wheel: Zoom Keys"),
                 ctrl | shift},
                {SelectNote, "selectNote",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Note: Select"), none},
                {ToggleNote, "toggleNote",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Note: Toggle"), ctrl},
                {ExtendNotes, "extendNotes",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Note: Extend"), shift},
                {MoveNotes, "moveNotes",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Drag Note: Move"), none},
                {PlainLength, "plainLength",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers",
                                   "Drag Note End: Fill with Rest"),
                 none},
                {FreeLength, "freeLength",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers",
                                   "Drag Note End: Move Next Notes"),
                 shift},
                {TakeFromNextNote, "takeFromNextNote",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers",
                                   "Drag Note End: Take from Next Note"),
                 ctrl},
                {SelectPoint, "selectPoint",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Point: Select"), none},
                {TogglePoint, "togglePoint",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Point: Toggle"), ctrl},
                {MovePoints, "movePoints",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Drag Point: Move"), none},
                {ClearSelection, "clearSelection",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Click Blank: Clear Selection"),
                 none},
                {ReplaceBand, "replaceBand",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Band: Select"), none},
                {AddToBand, "addToBand",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Band: Add"), shift},
                {ToggleBand, "toggleBand",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Band: Toggle"), ctrl},
                {PlainDraw, "plainDraw",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Pen: Draw"), none},
                {FillDraw, "fillDraw",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Pen: Draw Filling with Rest"),
                 shift},
                {DrawPitch, "drawPitch",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Pitch Tool: Draw"), none},
                {ErasePitch, "erasePitch",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Pitch Tool: Erase"), none},
                {DragVibrato, "dragVibrato",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Drag Vibrato: Edit"), none},
                {DragZoom, "dragZoom",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Drag: Zoom"), ctrl | alt},
                {DragZoomAxisLock, "dragZoomAxisLock",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Zoom: Lock Direction"), shift},
                {DisableNoteSnap, "disableNoteSnap",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Toggle: Disable Note Snap"),
                 alt},
                {PointSnapTime, "pointSnapTime",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers",
                                   "Drag Point: Snap to Other Points"),
                 shift},
                {PointSnapPitch, "pointSnapPitch",
                 QT_TRANSLATE_NOOP("hello::daw::NoteViewModifiers", "Drag Point: Snap Pitch"),
                 ctrl},
            },
            {
                {WheelScene,
                 {{VerticalScroll}, {HorizontalScroll}, {TimeZoom}, {KeyZoom}}},
                {NoteClickScene, {{SelectNote}, {ToggleNote}, {ExtendNotes}}},
                {NoteDragScene, {{MoveNotes}, zoom}},
                {NoteEndDragScene,
                 {{PlainLength, {DisableNoteSnap}},
                  {FreeLength, {DisableNoteSnap}},
                  {TakeFromNextNote, {DisableNoteSnap}},
                  zoom}},
                {PointClickScene, {{SelectPoint}, {TogglePoint}}},
                {PointDragScene, {{MovePoints, {PointSnapTime, PointSnapPitch}}, zoom}},
                {BlankClickScene, {{ClearSelection}}},
                {BandDragScene, {{ReplaceBand}, {AddToBand}, {ToggleBand}, zoom}},
                {DrawClickScene,
                 {{PlainDraw, {DisableNoteSnap}}, {FillDraw, {DisableNoteSnap}}}},
                {DrawDragScene,
                 {{PlainDraw, {DisableNoteSnap}}, {FillDraw, {DisableNoteSnap}}, zoom}},
                {SpanScene, {{ReplaceBand}, {AddToBand}, {ToggleBand}}},
                {PitchDrawScene, {{DrawPitch}, zoom}},
                {PitchEraseScene, {{ErasePitch}}},
                {VibratoDragScene, {{DragVibrato}, zoom}},
            });
        return scheme;
    }

}
