#ifndef HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H
#define HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H

#include <stdcorelib/stdc_global.h>

#ifndef HELLOUTAU_WIDGETS_EXPORT
#  ifdef HELLOUTAU_WIDGETS_STATIC
#    define HELLOUTAU_WIDGETS_EXPORT
#  else
#    ifdef HELLOUTAU_WIDGETS_LIBRARY
#      define HELLOUTAU_WIDGETS_EXPORT STDC_DECL_EXPORT
#    else
#      define HELLOUTAU_WIDGETS_EXPORT STDC_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H
