#ifndef HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H
#define HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOUTAU_WIDGETS_EXPORT
#  ifdef HELLOUTAU_WIDGETS_STATIC
#    define HELLOUTAU_WIDGETS_EXPORT
#  else
#    ifdef HELLOUTAU_WIDGETS_LIBRARY
#      define HELLOUTAU_WIDGETS_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOUTAU_WIDGETS_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_WIDGETS_HELLOUTAUWIDGETSGLOBAL_H
