#ifndef HELLOUTAU_THEME_HELLOUTAUTHEMEGLOBAL_H
#define HELLOUTAU_THEME_HELLOUTAUTHEMEGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOUTAU_THEME_EXPORT
#  ifdef HELLOUTAU_THEME_STATIC
#    define HELLOUTAU_THEME_EXPORT
#  else
#    ifdef HELLOUTAU_THEME_LIBRARY
#      define HELLOUTAU_THEME_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOUTAU_THEME_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_THEME_HELLOUTAUTHEMEGLOBAL_H
