#include <filesystem>
#include <fstream>

#include <QtCore/QPointer>
#include <QtCore/QTemporaryDir>
#include <QtGui/QAction>
#include <QtTest/QTest>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>

#include <QAKCore/actionregistry.h>
#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Widgets/ActionContributionRegistry.h>
#include <helloutau/Editor/AppSettings.h>
#include <helloutau/Editor/BuiltinActions.h>
#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>
#include <helloutau/Editor/VoiceBankWindow.h>

// Generated by qak_add_action_extension() from TestContribution.xml and TestBankContribution.xml
#include "TestBankContribution.qak.h"
#include "TestContribution.qak.h"

using namespace hello::daw;

namespace fs = std::filesystem;

namespace {

    const QString HelloId = QStringLiteral("test.contribution.hello");
    const QString BankId = QStringLiteral("test.contribution.bank");
    const QString MenuId = QStringLiteral("test.contribution.menu");

    // Contribution of TestContribution.xml, Hello in project windows, which counts its
    // triggers, and of TestBankContribution.xml, Bank Hello in voice bank windows
    class TestContribution : public ActionContribution {
    public:
        explicit TestContribution(int *triggered) : m_triggered(triggered) {
        }

        const QAK::ActionExtension *extension(const QString &windowKind) const override {
            return windowKind == QLatin1String(Editor::projectWindowName)
                       ? test::testContribution()
                       : test::testBankContribution();
        }

        void addActions(QWidget *window, QAK::WidgetActionContext *context) override {
            if (qobject_cast<VoiceBankWindow *>(window)) {
                context->addAction(BankId, new QAction(window));
                return;
            }
            const auto action = new QAction(window);
            QObject::connect(action, &QAction::triggered, [this] { ++*m_triggered; });
            context->addAction(HelloId, action);
            // An external item, whose action is the menu action owned by the menu
            context->addAction(MenuId, (new QMenu(window))->menuAction());
        }

    private:
        int *m_triggered;
    };

    ActionContributionRegistry::AddFactory registration(Editor *editor, int *triggered) {
        return ActionContributionRegistry::AddFactory(
            editor->actionContributions(), "test.contribution", {},
            [triggered] { return std::make_unique<TestContribution>(triggered); });
    }

    // Returns the item texts of the menu titled \a title in the menu bar of \a window.
    QStringList menuTexts(QMainWindow *window, const QString &title) {
        QStringList texts;
        for (const auto action : window->menuBar()->actions()) {
            if (action->text() == title && action->menu()) {
                for (const auto item : action->menu()->actions()) {
                    texts.push_back(item->text());
                }
            }
        }
        return texts;
    }

}

class test_ActionContribution : public QObject {
    Q_OBJECT

    QTemporaryDir m_dir;

    // An editor with its own menus registered, into which the contributions insert their items
    std::unique_ptr<Editor> editor() const {
        auto e = std::make_unique<Editor>(
            std::make_unique<AppSettings>(m_dir.filePath(QStringLiteral("settings.json"))));
        e->setWatchesDisk(false);
        new BuiltinActions(e.get());
        return e;
    }

    // Returns a voice bank that records its encoding, so that the user is not prompted.
    fs::path voiceBank() const {
        const auto bank = fs::path(m_dir.path().toStdU16String()) / "bank";
        fs::create_directories(bank);
        std::ofstream(bank / "oto.ini", std::ios::binary)
            << "#Charset:UTF-8\r\na.wav=a,10,20,-30,40,5\r\n";
        std::ofstream(bank / "a.wav", std::ios::binary);
        return bank;
    }

private Q_SLOTS:
    // The windows open at the time of registration receive the actions, as do the windows
    // opened later. All windows lose the actions when the registration is destroyed.
    void a_registration_reaches_the_open_windows_and_ends_with_them() {
        const auto e = editor();
        const auto first = e->newWindow();
        QVERIFY(!e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(HelloId));

        int triggered = 0;
        auto reg = registration(e.get(), &triggered);
        const auto second = e->newWindow();
        const auto info = e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(HelloId);
        QVERIFY(info);
        QVERIFY(info->isCommand());
        QList<QPointer<QAction>> actions;
        for (const auto window : {first, second}) {
            const auto action = window->actionContext()->action(HelloId);
            QVERIFY(action);
            QCOMPARE(action->parent(), window);
            QVERIFY(menuTexts(window, QStringLiteral("&Tools")).contains(QStringLiteral("Hello")));
            QVERIFY(!window->actionContext()->action(BankId));
            actions.push_back(action);
        }
        first->actionContext()->action(HelloId)->trigger();
        QCOMPARE(triggered, 1);

        reg = {};
        QVERIFY(!e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(HelloId));
        for (const auto window : {first, second}) {
            QVERIFY(!window->actionContext()->action(HelloId));
            QVERIFY(!menuTexts(window, QStringLiteral("&Tools")).contains(QStringLiteral("Hello")));
        }
        for (const auto &action : std::as_const(actions)) {
            QVERIFY(action.isNull());
        }
    }

    // The menu of an external item is deleted with the registration, together with its action,
    // which the menu owns.
    void an_external_menu_goes_with_its_registration() {
        const auto e = editor();
        int triggered = 0;
        auto reg = registration(e.get(), &triggered);
        const auto window = e->newWindow();
        const auto action = window->actionContext()->action(MenuId);
        QVERIFY(action);
        const QPointer<QMenu> menu = qobject_cast<QMenu *>(action->parent());
        QVERIFY(menu);
        QCOMPARE(menu->menuAction(), action);
        QCOMPARE(menu->parent(), window);

        reg = {};
        QVERIFY(menu.isNull());
        QVERIFY(!window->actionContext()->action(MenuId));
    }

    // A voice bank window receives its own actions, and each extension is in the registry of
    // its kind of window alone.
    void each_kind_of_window_receives_its_own_extension() {
        const auto e = editor();
        int triggered = 0;
        const auto reg = registration(e.get(), &triggered);
        QVERIFY(e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(HelloId));
        QVERIFY(!e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(BankId));
        QVERIFY(e->actionRegistry(Editor::VoiceBankWindowKind)->actionInfo(BankId));
        QVERIFY(!e->actionRegistry(Editor::VoiceBankWindowKind)->actionInfo(HelloId));
        const auto window = e->newWindow();
        QVERIFY(window->actionContext()->action(HelloId));

        const auto bank = e->openVoiceBank(voiceBank());
        QVERIFY(bank);
        // Created by the contribution, not a placeholder created by the context
        const auto bankAction = bank->actionContext()->action(BankId);
        QVERIFY(bankAction);
        QCOMPARE(bankAction->parent(), bank);
        QVERIFY(!bank->actionContext()->action(HelloId));
        QVERIFY(menuTexts(bank, QStringLiteral("&Tools")).contains(QStringLiteral("Bank Hello")));
    }

    // A registration may outlive the editor of its registry, and its destruction then removes
    // nothing.
    void a_registration_outlives_an_editor() {
        int triggered = 0;
        ActionContributionRegistry::AddFactory reg;
        {
            const auto e = editor();
            reg = registration(e.get(), &triggered);
            e->newWindow();
        }
        reg = {};

        // Another editor has no action of the contribution.
        const auto e = editor();
        QVERIFY(!e->actionRegistry(Editor::ProjectWindowKind)->actionInfo(HelloId));
    }
};

int main(int argc, char *argv[]) {
    // Runs without a display
    qputenv("QT_QPA_PLATFORM", "offscreen");
    QApplication app(argc, argv);
    test_ActionContribution test;
    return QTest::qExec(&test, argc, argv);
}

#include "test_ActionContribution.moc"
