#include <filesystem>
#include <fstream>

#include <QtCore/QPointer>
#include <QtCore/QTemporaryDir>
#include <QtGui/QAction>
#include <QtTest/QTest>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>

#include <QAKCore/actionregistry.h>
#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Editor/ActionContribution.h>
#include <helloutau/Editor/ActionRegistration.h>
#include <helloutau/Editor/AppSettings.h>
#include <helloutau/Editor/BuiltinActions.h>
#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>
#include <helloutau/Editor/VoiceBankWindow.h>

// Generated by qak_add_action_extension() from TestContribution.xml
#include "TestContribution.qak.h"

using namespace hello::daw;

namespace fs = std::filesystem;

namespace {

    const QString HelloId = QStringLiteral("test.contribution.hello");
    const QString BankId = QStringLiteral("test.contribution.bank");

    // The contribution of TestContribution.xml: Hello in project windows, which counts its
    // triggers, and Bank Hello in voice bank windows
    class TestContribution : public ActionContribution {
    public:
        explicit TestContribution(int *triggered) : m_triggered(triggered) {
        }

        const QAK::ActionExtension *extension() const override {
            return test::testContribution();
        }

        void addActions(ProjectWindow *window, QAK::WidgetActionContext *context) override {
            const auto action = new QAction(window);
            QObject::connect(action, &QAction::triggered, [this] { ++*m_triggered; });
            context->addAction(HelloId, action);
        }

        void addActions(VoiceBankWindow *window, QAK::WidgetActionContext *context) override {
            context->addAction(BankId, new QAction(window));
        }

    private:
        int *m_triggered;
    };

    std::unique_ptr<ActionRegistration> registration(int *triggered) {
        return std::make_unique<ActionRegistration>(std::make_unique<TestContribution>(triggered));
    }

    // The texts of the menu of the menu bar of window whose title is title
    QStringList menuTexts(QMainWindow *window, const QString &title) {
        QStringList texts;
        for (const auto action : window->menuBar()->actions()) {
            if (action->text() == title && action->menu()) {
                for (const auto item : action->menu()->actions()) {
                    texts.push_back(item->text());
                }
            }
        }
        return texts;
    }

}

class test_ActionContribution : public QObject {
    Q_OBJECT

    QTemporaryDir m_dir;
    // The menus of the editor, which the contributions insert into
    BuiltinActions m_actions;

    std::unique_ptr<Editor> editor() const {
        auto e = std::make_unique<Editor>(
            std::make_unique<AppSettings>(m_dir.filePath(QStringLiteral("settings.ini"))));
        e->setWatchesDisk(false);
        return e;
    }

    // A voice bank that declares its encoding, so that nothing is asked
    fs::path voiceBank() const {
        const auto bank = fs::path(m_dir.path().toStdU16String()) / "bank";
        fs::create_directories(bank);
        std::ofstream(bank / "oto.ini", std::ios::binary)
            << "#Charset:UTF-8\r\na.wav=a,10,20,-30,40,5\r\n";
        std::ofstream(bank / "a.wav", std::ios::binary);
        return bank;
    }

private Q_SLOTS:
    // The windows open at the registration take the actions, as do those opened after it, and
    // they all lose them with the registration.
    void a_registration_reaches_the_open_windows_and_ends_with_them() {
        const auto e = editor();
        const auto first = e->newWindow();
        QVERIFY(!e->actionRegistry()->actionInfo(HelloId));

        int triggered = 0;
        auto reg = registration(&triggered);
        const auto second = e->newWindow();
        const auto info = e->actionRegistry()->actionInfo(HelloId);
        QVERIFY(info);
        QVERIFY(info->isCommand());
        QList<QPointer<QAction>> actions;
        for (const auto window : {first, second}) {
            const auto action = window->actionContext()->action(HelloId);
            QVERIFY(action);
            QCOMPARE(action->parent(), window);
            QVERIFY(menuTexts(window, QStringLiteral("&Tools")).contains(QStringLiteral("Hello")));
            QVERIFY(!window->actionContext()->action(BankId));
            actions.push_back(action);
        }
        first->actionContext()->action(HelloId)->trigger();
        QCOMPARE(triggered, 1);

        reg.reset();
        QVERIFY(!e->actionRegistry()->actionInfo(HelloId));
        for (const auto window : {first, second}) {
            QVERIFY(!window->actionContext()->action(HelloId));
            QVERIFY(!menuTexts(window, QStringLiteral("&Tools")).contains(QStringLiteral("Hello")));
        }
        for (const auto &action : std::as_const(actions)) {
            QVERIFY(action.isNull());
        }
    }

    // An editor created after the registration takes it, a voice bank window its own actions.
    void an_editor_takes_the_registrations_before_it() {
        int triggered = 0;
        const auto reg = registration(&triggered);
        const auto e = editor();
        QVERIFY(e->actionRegistry()->actionInfo(HelloId));
        const auto window = e->newWindow();
        QVERIFY(window->actionContext()->action(HelloId));

        const auto bank = e->openVoiceBank(voiceBank());
        QVERIFY(bank);
        // Created by the contribution, rather than as a stand-in by the context
        const auto bankAction = bank->actionContext()->action(BankId);
        QVERIFY(bankAction);
        QCOMPARE(bankAction->parent(), bank);
        QVERIFY(!bank->actionContext()->action(HelloId));
        QVERIFY(menuTexts(bank, QStringLiteral("&Tools")).contains(QStringLiteral("Bank Hello")));
    }

    // A registration may outlive the editor.
    void a_registration_outlives_an_editor() {
        int triggered = 0;
        auto reg = registration(&triggered);
        {
            const auto e = editor();
            e->newWindow();
        }
        reg.reset();

        // A later editor has none of it.
        const auto e = editor();
        QVERIFY(!e->actionRegistry()->actionInfo(HelloId));
    }
};

int main(int argc, char *argv[]) {
    // Runs without a display
    qputenv("QT_QPA_PLATFORM", "offscreen");
    QApplication app(argc, argv);
    test_ActionContribution test;
    return QTest::qExec(&test, argc, argv);
}

#include "test_ActionContribution.moc"
