#ifndef HELLOKIT_INTERCHANGE_HELLOKITINTERCHANGEGLOBAL_H
#define HELLOKIT_INTERCHANGE_HELLOKITINTERCHANGEGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_INTERCHANGE_EXPORT
#  ifdef HELLOKIT_INTERCHANGE_STATIC
#    define HELLOKIT_INTERCHANGE_EXPORT
#  else
#    ifdef HELLOKIT_INTERCHANGE_LIBRARY
#      define HELLOKIT_INTERCHANGE_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_INTERCHANGE_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_INTERCHANGE_HELLOKITINTERCHANGEGLOBAL_H
