#ifndef HELLOUTAU_AUDIO_HELLOUTAUAUDIOGLOBAL_H
#define HELLOUTAU_AUDIO_HELLOUTAUAUDIOGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOUTAU_AUDIO_EXPORT
#  ifdef HELLOUTAU_AUDIO_STATIC
#    define HELLOUTAU_AUDIO_EXPORT
#  else
#    ifdef HELLOUTAU_AUDIO_LIBRARY
#      define HELLOUTAU_AUDIO_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOUTAU_AUDIO_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_AUDIO_HELLOUTAUAUDIOGLOBAL_H
