#ifndef HELLOKIT_SUPPORT_HELLOKITSUPPORTGLOBAL_H
#define HELLOKIT_SUPPORT_HELLOKITSUPPORTGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_SUPPORT_EXPORT
#  ifdef HELLOKIT_SUPPORT_STATIC
#    define HELLOKIT_SUPPORT_EXPORT
#  else
#    ifdef HELLOKIT_SUPPORT_LIBRARY
#      define HELLOKIT_SUPPORT_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_SUPPORT_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_SUPPORT_HELLOKITSUPPORTGLOBAL_H
