#ifndef HELLOKIT_SYNTH_HELLOKITSYNTHGLOBAL_H
#define HELLOKIT_SYNTH_HELLOKITSYNTHGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_SYNTH_EXPORT
#  ifdef HELLOKIT_SYNTH_STATIC
#    define HELLOKIT_SYNTH_EXPORT
#  else
#    ifdef HELLOKIT_SYNTH_LIBRARY
#      define HELLOKIT_SYNTH_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_SYNTH_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_SYNTH_HELLOKITSYNTHGLOBAL_H
