#include <memory>

#include <QtCore/QCoreApplication>
#include <QtCore/QVariant>
#include <QtGui/QAction>

#include <stdcorelib/pluginsystem/iplugin.h>

#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Editor/AppLoader.h>
#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>
#include <helloutau/Widgets/ActionContributionRegistry.h>

// Generated by qak_add_action_extension() from TestActions.xml
#include "TestActions.qak.h"

namespace {

    using namespace hello::daw;

    // Contribution of Hello in the Tools menu of the project window. The command counts its
    // triggers in the property testActionTriggered of the application.
    class TestActionContribution : public ActionContribution {
    public:
        const QAK::ActionExtension *extension(const QString &windowKind) const override {
            return windowKind == QLatin1String(Editor::projectWindowName) ? test::testActions()
                                                                          : nullptr;
        }

        void addActions(QWidget *window, QAK::WidgetActionContext *context) override {
            if (!qobject_cast<ProjectWindow *>(window)) {
                return;
            }
            const auto action = new QAction(window);
            QObject::connect(action, &QAction::triggered, [] {
                qApp->setProperty("testActionTriggered",
                                  qApp->property("testActionTriggered").toInt() + 1);
            });
            // Copied from UTF-8 instead of a literal, whose text becomes invalid when this library
            // is unloaded
            context->addAction(QString::fromUtf8("helloutau.test.hello"), action);
        }
    };

    /// Test plugin that adds the command Hello to the project windows.
    class TestActionPlugin : public stdc::pluginsystem::IPlugin {
    public:
        bool initialize(std::string *errorMessage) override {
            const auto loader = AppLoader::instance();
            const auto editor = loader ? loader->editor() : nullptr;
            if (!editor) {
                if (errorMessage) {
                    *errorMessage = "The editor of the core plugin does not exist.";
                }
                return false;
            }
            m_registration = ActionContributionRegistry::AddFactory(
                editor->actionContributions(), "org.helloutau.test.action", {},
                [] { return std::make_unique<TestActionContribution>(); });
            return true;
        }

        void aboutToShutdown() override {
            m_registration = {};
        }

    private:
        ActionContributionRegistry::AddFactory m_registration;
    };

}

STDC_EXPORT_PLUGIN(TestActionPlugin)
