#ifndef HELLOKIT_VOICEBANK_HELLOKITVOICEBANKGLOBAL_H
#define HELLOKIT_VOICEBANK_HELLOKITVOICEBANKGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_VOICEBANK_EXPORT
#  ifdef HELLOKIT_VOICEBANK_STATIC
#    define HELLOKIT_VOICEBANK_EXPORT
#  else
#    ifdef HELLOKIT_VOICEBANK_LIBRARY
#      define HELLOKIT_VOICEBANK_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_VOICEBANK_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_VOICEBANK_HELLOKITVOICEBANKGLOBAL_H
