#include "InterchangeContribution.h"

#include <QtGui/QAction>

#include <QAKWidgets/widgetactioncontext.h>

#include <helloutau/Editor/Editor.h>
#include <helloutau/Editor/ProjectWindow.h>

#include <Interchange/InterchangeService.h>

#include "ExportWizard.h"
#include "ImportWizard.h"

// Generated by qak_add_action_extension() from InterchangeActions.xml
#include "InterchangeActions.qak.h"

namespace hello::daw {

    InterchangeContribution::InterchangeContribution(InterchangeService *service)
        : m_service(service) {
    }

    InterchangeContribution::~InterchangeContribution() = default;

    // Projects are imported and exported from the project window alone.
    const QAK::ActionExtension *
        InterchangeContribution::extension(const QString &windowKind) const {
        return windowKind == QLatin1String(Editor::projectWindowName) ? interchangeActions()
                                                                      : nullptr;
    }

    void InterchangeContribution::addActions(QWidget *widget, QAK::WidgetActionContext *context) {
        const auto window = qobject_cast<ProjectWindow *>(widget);
        if (!window) {
            return;
        }
        const auto service = m_service;
        const auto importAction = new QAction(window);
        QObject::connect(importAction, &QAction::triggered, window, [window, service] {
            ImportWizard wizard(window, service);
            wizard.exec();
        });
        const auto exportAction = new QAction(window);
        QObject::connect(exportAction, &QAction::triggered, window, [window, service] {
            ExportWizard wizard(window, &service->drivers());
            wizard.exec();
        });
        // Allocated copies rather than literals, because the text of a literal is unloaded with
        // this library
        context->addAction(QString::fromUtf8("helloutau.file.import"), importAction);
        context->addAction(QString::fromUtf8("helloutau.file.exportOther"), exportAction);
    }

}
