#ifndef HELLOKIT_EDITBASE_HELLOKITEDITBASEGLOBAL_H
#define HELLOKIT_EDITBASE_HELLOKITEDITBASEGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_EDITBASE_EXPORT
#  ifdef HELLOKIT_EDITBASE_STATIC
#    define HELLOKIT_EDITBASE_EXPORT
#  else
#    ifdef HELLOKIT_EDITBASE_LIBRARY
#      define HELLOKIT_EDITBASE_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_EDITBASE_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_EDITBASE_HELLOKITEDITBASEGLOBAL_H
