#ifndef HELLOKIT_EDIT_HELLOKITEDITGLOBAL_H
#define HELLOKIT_EDIT_HELLOKITEDITGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef HELLOKIT_EDIT_EXPORT
#  ifdef HELLOKIT_EDIT_STATIC
#    define HELLOKIT_EDIT_EXPORT
#  else
#    ifdef HELLOKIT_EDIT_LIBRARY
#      define HELLOKIT_EDIT_EXPORT Q_DECL_EXPORT
#    else
#      define HELLOKIT_EDIT_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOKIT_EDIT_HELLOKITEDITGLOBAL_H
