#ifndef HELLOUTAU_INTERCHANGE_INTERCHANGEPLUGINGLOBAL_H
#define HELLOUTAU_INTERCHANGE_INTERCHANGEPLUGINGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef INTERCHANGEPLUGIN_EXPORT
#  ifdef INTERCHANGEPLUGIN_STATIC
#    define INTERCHANGEPLUGIN_EXPORT
#  else
#    ifdef INTERCHANGEPLUGIN_LIBRARY
#      define INTERCHANGEPLUGIN_EXPORT Q_DECL_EXPORT
#    else
#      define INTERCHANGEPLUGIN_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_INTERCHANGE_INTERCHANGEPLUGINGLOBAL_H
