#ifndef HELLOUTAU_CLASSICPLUGINHOST_CLASSICPLUGINHOSTPLUGINGLOBAL_H
#define HELLOUTAU_CLASSICPLUGINHOST_CLASSICPLUGINHOSTPLUGINGLOBAL_H

#include <QtCore/QtGlobal>

#ifndef CLASSICPLUGINHOST_EXPORT
#  ifdef CLASSICPLUGINHOST_STATIC
#    define CLASSICPLUGINHOST_EXPORT
#  else
#    ifdef CLASSICPLUGINHOST_LIBRARY
#      define CLASSICPLUGINHOST_EXPORT Q_DECL_EXPORT
#    else
#      define CLASSICPLUGINHOST_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // HELLOUTAU_CLASSICPLUGINHOST_CLASSICPLUGINHOSTPLUGINGLOBAL_H
